name: pushy_flutter
description: The official Pushy SDK for Flutter apps.
version: 2.0.43
homepage: https://pushy.me/
repository: https://github.com/pushy/pushy-flutter

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.12.0"

dependencies:
  universal_html: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.pushy.sdk.flutter
        pluginClass: PushyPlugin
      ios:
        pluginClass: PushyPlugin
